In [2]:
import numpy as np
array1 = np.array([1, 2, 3])
print('array1 datatype:', type(array1), array1.shape)

array1 datatype: <class 'numpy.ndarray'> (3,)


In [8]:
array2 = np.array([[1, 2, 3], [5, 878, 11]])
print(array2.shape)

(2, 3)


In [9]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3.shape)

(2, 2, 3)


In [13]:
array4 = np.array([1, 2, 'test'])
array4.dtype

dtype('<U11')

In [16]:
array_int = array1.astype('float64')
print(array_int, array_int.dtype, type(array_int))

[1. 2. 3.] float64 <class 'numpy.ndarray'>


In [19]:
sequence_array = np.arange(2, 10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[2 3 4 5 6 7 8 9]
int32 (8,)


In [25]:
zero_array = np.ones((3, 2), dtype = 'int32')
print(zero_array, zero_array.shape)

[[1 1]
 [1 1]
 [1 1]] (3, 2)


In [30]:
array1 = np.arange(10)
array11 = array1.reshape(2, 5)
array22 = array1.reshape(5, 2)
print(array11, '\n\n', array22)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 2)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [34]:
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2)
print('array3d:\n', array3d)
print('\n')
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5)
array6 = array1.reshape(-1, 1)
print('array6:\n', array6)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array5:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [4]:
array1 = np.arange(1, 10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
